/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as ClinicalRouteImport } from './routes/clinical'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalRoute = ClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clinical': typeof ClinicalRoute
  '/documents': typeof DocumentsRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRouteWithChildren
  '/visits': typeof VisitsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clinical': typeof ClinicalRoute
  '/documents': typeof DocumentsRoute
  '/orders': typeof OrdersRoute
  '/visits': typeof VisitsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/clinical': typeof ClinicalRoute
  '/documents': typeof DocumentsRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRouteWithChildren
  '/visits': typeof VisitsRoute
  '/patients/$id': typeof PatientsIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/clinical'
    | '/documents'
    | '/orders'
    | '/patients'
    | '/visits'
    | '/patients/$id'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/clinical'
    | '/documents'
    | '/orders'
    | '/visits'
    | '/patients/$id'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/clinical'
    | '/documents'
    | '/orders'
    | '/patients'
    | '/visits'
    | '/patients/$id'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ClinicalRoute: typeof ClinicalRoute
  DocumentsRoute: typeof DocumentsRoute
  OrdersRoute: typeof OrdersRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  VisitsRoute: typeof VisitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical': {
      id: '/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof ClinicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  ClinicalRoute: ClinicalRoute,
  DocumentsRoute: DocumentsRoute,
  OrdersRoute: OrdersRoute,
  PatientsRoute: PatientsRouteWithChildren,
  VisitsRoute: VisitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
